
var dadosGraficoBarraVertical = function(){
    return {  
    "conjutoDados":[  
        {  
        "descricaoConjunto":"Descricao 1a",
        "exibirValores":true,
        "listaValores":[  
            {  
            "corItem":-65536,
            "corTexto":-16777216,
            "hashConjuntoDado":715913675,
            "valorX":0.0,
            "valorY":0.0
            },
            {  
            "corItem":-65536,
            "corTexto":-16777216,
            "hashConjuntoDado":715913675,
            "valorX":0.0,
            "valorY":1200.0
            }
        ],
        "tamanhoTextoItens":14.0,
        "tipoFormatacao":"MONETARIO"
        },
        {  
        "descricaoConjunto":"Descricao 2a",
        "exibirValores":true,
        "listaValores":[  
            {  
            "corItem":-16776961,
            "corTexto":-16777216,
            "hashConjuntoDado":715914636,
            "valorX":1.0,
            "valorY":0.0
            },
            {  
            "corItem":-16776961,
            "corTexto":-16777216,
            "hashConjuntoDado":715914636,
            "valorX":1.0,
            "valorY":1400.0
            }
        ],
        "tamanhoTextoItens":14.0,
        "tipoFormatacao":"MONETARIO"
        }
    ],
    "corCentroPizza":0,
    "descricaoGrafico":{  
        "alinhamento":"CENTER",
        "cor":-16777216,
        "habilitar":false,
        "posicaoEixoX":10.0,
        "posicaoEixoY":20.0,
        "tamanhoFonte":15.0,
        "texto":"Vertical"
    },
    "eixoX":{  
        "corGrade":-16777216,
        "espessuraGrade":"FINO",
        "exibirGrade":false,
        "exibirLabel":false,
        "formatacao":"",
        "habilitado":false,
        "label":{  
        "cor":-16777216,
        "habilitar":false,
        "posicaoEixoX":0.0,
        "posicaoEixoY":0.0,
        "tamanhoFonte":14.0,
        "texto":"Eixo X"
        },
        "tipoEixo":"EIXO_X",
        "tipoFormatacao":"MONETARIO",
        "valorMaximo":3.0,
        "valorMinimo":0.0
    },
    "eixoY":{  
        "corGrade":-16777216,
        "espessuraGrade":"FINO",
        "exibirGrade":false,
        "exibirLabel":false,
        "formatacao":"",
        "habilitado":false,
        "label":{  
        "cor":-16777216,
        "habilitar":false,
        "posicaoEixoX":0.0,
        "posicaoEixoY":0.0,
        "tamanhoFonte":14.0,
        "texto":"EIXO_Y_ESQUERDA"
        },
        "tipoEixo":"EIXO_Y_ESQUERDA",
        "tipoFormatacao":"MONETARIO",
        "valorMaximo":1680.0,
        "valorMinimo":0.0
    },
    "estilo":{  
        "corDaBorda":-16777216,
        "corDeFundo":0,
        "corDeFundoGrade":0,
        "corLegendas":-16777216,
        "espessuraBorda":"FINO",
        "exibirBordas":false,
        "exibirGradeDeFundo":false,
        "habilitarLegendas":true,
        "tamanhoTextoLegendas":"NORMAL"
    },
    "habilitarArrastar":false,
    "habilitarBuracoCentroPizza":false,
    "habilitarDestaqueAoToquePizza":true,
    "habilitarGirarAoToque":false,
    "habilitarToque":false,
    "habilitarValoresPorPorcentagemPizza":false,
    "habilitarZoom":false,
    "incluirDescricaoDentroDoGrafico":false,
    "larguraBarra":0.8,
    "porcentagemRaioCentroPizza":50.0,
    "porcentagemTransparenciaCentroPizza":55.0,
    "tamanhoDestaquePorcaoSelecionadaPizza":18.0,
    "tipo":"BARRA_VERTICAL",
    "tipoAnimacao":"NORMAL"
    };
}

exports.barraVertical = function(callback){
    callback(dadosGraficoBarraVertical());
};