
var dadosGraficoBarraHorizontal = function(){
    return {  
  'conjutoDados':[  
    {  
      'descricaoConjunto':'Descricao 1h',
      'exibirValores':true,
      'listaValores':[  
        {  
          'corItem':-65536,
          'corTexto':-16777216,
          'hashConjuntoDado':715913892,
          'valorX':0.0,
          'valorY':0.0
        },
        {  
          'corItem':-65536,
          'corTexto':-16777216,
          'hashConjuntoDado':715913892,
          'valorX':0.0,
          'valorY':1200.0
        }
      ],
      'tamanhoTextoItens':14.0,
      'tipoFormatacao':'MONETARIO'
    },
    {  
      'descricaoConjunto':'Descricao 2h',
      'exibirValores':true,
      'listaValores':[  
        {  
          'corItem':-16776961,
          'corTexto':-16777216,
          'hashConjuntoDado':715914853,
          'valorX':1.0,
          'valorY':0.0
        },
        {  
          'corItem':-16776961,
          'corTexto':-16777216,
          'hashConjuntoDado':715914853,
          'valorX':1.0,
          'valorY':1400.0
        }
      ],
      'tamanhoTextoItens':14.0,
      'tipoFormatacao':'MONETARIO'
    }
  ],
  'corCentroPizza':0,
  'descricaoGrafico':{  
    'alinhamento':'CENTER',
    'cor':-16777216,
    'habilitar':false,
    'posicaoEixoX':10.0,
    'posicaoEixoY':20.0,
    'tamanhoFonte':15.0,
    'texto':'Horizontal'
  },
  'eixoX':{  
    'corGrade':-16777216,
    'espessuraGrade':'FINO',
    'exibirGrade':false,
    'exibirLabel':false,
    'formatacao':'',
    'habilitado':false,
    'label':{  
      'cor':-16777216,
      'habilitar':false,
      'posicaoEixoX':0.0,
      'posicaoEixoY':0.0,
      'tamanhoFonte':14.0,
      'texto':'Eixo X'
    },
    'tipoEixo':'EIXO_X',
    'tipoFormatacao':'MONETARIO',
    'valorMaximo':3.0,
    'valorMinimo':0.0
  },
  'eixoY':{  
    'corGrade':-16777216,
    'espessuraGrade':'FINO',
    'exibirGrade':false,
    'exibirLabel':false,
    'formatacao':'',
    'habilitado':false,
    'label':{  
      'cor':-16777216,
      'habilitar':false,
      'posicaoEixoX':0.0,
      'posicaoEixoY':0.0,
      'tamanhoFonte':14.0,
      'texto':'EIXO_Y_ESQUERDA'
    },
    'tipoEixo':'EIXO_Y_ESQUERDA',
    'tipoFormatacao':'MONETARIO',
    'valorMaximo':1680.0,
    'valorMinimo':0.0
  },
  'estilo':{  
    'corDaBorda':-16777216,
    'corDeFundo':0,
    'corDeFundoGrade':0,
    'corLegendas':-16777216,
    'espessuraBorda':'FINO',
    'exibirBordas':false,
    'exibirGradeDeFundo':false,
    'habilitarLegendas':true,
    'tamanhoTextoLegendas':'NORMAL'
  },
  'habilitarArrastar':false,
  'habilitarBuracoCentroPizza':false,
  'habilitarDestaqueAoToquePizza':true,
  'habilitarGirarAoToque':false,
  'habilitarToque':false,
  'habilitarValoresPorPorcentagemPizza':false,
  'habilitarZoom':false,
  'incluirDescricaoDentroDoGrafico':false,
  'larguraBarra':0.8,
  'porcentagemRaioCentroPizza':50.0,
  'porcentagemTransparenciaCentroPizza':55.0,
  'tamanhoDestaquePorcaoSelecionadaPizza':18.0,
  'tipo':'BARRA_HORIZONTAL',
  'tipoAnimacao':'NORMAL'
  }
};

var dadosGraficoLinha = function(){
    return {  
  "conjutoDados":[  
    {  
      "descricaoConjunto":"Descricao 1a",
      "exibirValores":true,
      "listaValores":[  
        {  
          "corItem":-65536,
          "corTexto":-16777216,
          "hashConjuntoDado":715913675,
          "valorX":1.0,
          "valorY":1.0
        },
        {  
          "corItem":-65536,
          "corTexto":-16777216,
          "hashConjuntoDado":715913675,
          "valorX":2.0,
          "valorY":2.05
        },
        {  
          "corItem":-65536,
          "corTexto":-16777216,
          "hashConjuntoDado":715913675,
          "valorX":3.0,
          "valorY":4.1
        },
        {  
          "corItem":-65536,
          "corTexto":-16777216,
          "hashConjuntoDado":715913675,
          "valorX":4.0,
          "valorY":8.2
        },
        {  
          "corItem":-65536,
          "corTexto":-16777216,
          "hashConjuntoDado":715913675,
          "valorX":5.0,
          "valorY":16.4
        },
        {  
          "corItem":-65536,
          "corTexto":-16777216,
          "hashConjuntoDado":715913675,
          "valorX":6.0,
          "valorY":32.8
        },
        {  
          "corItem":-65536,
          "corTexto":-16777216,
          "hashConjuntoDado":715913675,
          "valorX":7.0,
          "valorY":65.6
        },
        {  
          "corItem":-65536,
          "corTexto":-16777216,
          "hashConjuntoDado":715913675,
          "valorX":8.0,
          "valorY":131.2
        },
        {  
          "corItem":-65536,
          "corTexto":-16777216,
          "hashConjuntoDado":715913675,
          "valorX":9.0,
          "valorY":262.4
        },
        {  
          "corItem":-65536,
          "corTexto":-16777216,
          "hashConjuntoDado":715913675,
          "valorX":10.0,
          "valorY":524.8
        }
      ],
      "tamanhoTextoItens":14.0,
      "tipoFormatacao":"MONETARIO"
    },
    {  
      "descricaoConjunto":"Descricao 2a",
      "exibirValores":true,
      "listaValores":[  
        {  
          "corItem":-16776961,
          "corTexto":-16777216,
          "hashConjuntoDado":715914636,
          "valorX":1.0,
          "valorY":1.0
        },
        {  
          "corItem":-16776961,
          "corTexto":-16777216,
          "hashConjuntoDado":715914636,
          "valorX":2.0,
          "valorY":2.0
        },
        {  
          "corItem":-16776961,
          "corTexto":-16777216,
          "hashConjuntoDado":715914636,
          "valorX":3.0,
          "valorY":4.5
        },
        {  
          "corItem":-16776961,
          "corTexto":-16777216,
          "hashConjuntoDado":715914636,
          "valorX":4.0,
          "valorY":9.5
        },
        {  
          "corItem":-16776961,
          "corTexto":-16777216,
          "hashConjuntoDado":715914636,
          "valorX":5.0,
          "valorY":19.5
        },
        {  
          "corItem":-16776961,
          "corTexto":-16777216,
          "hashConjuntoDado":715914636,
          "valorX":6.0,
          "valorY":39.5
        },
        {  
          "corItem":-16776961,
          "corTexto":-16777216,
          "hashConjuntoDado":715914636,
          "valorX":7.0,
          "valorY":79.5
        },
        {  
          "corItem":-16776961,
          "corTexto":-16777216,
          "hashConjuntoDado":715914636,
          "valorX":8.0,
          "valorY":159.5
        },
        {  
          "corItem":-16776961,
          "corTexto":-16777216,
          "hashConjuntoDado":715914636,
          "valorX":9.0,
          "valorY":319.5
        },
        {  
          "corItem":-16776961,
          "corTexto":-16777216,
          "hashConjuntoDado":715914636,
          "valorX":10.0,
          "valorY":639.5
        }
      ],
      "tamanhoTextoItens":14.0,
      "tipoFormatacao":"MONETARIO"
    }
  ],
  "corCentroPizza":0,
  "descricaoGrafico":{  
    "alinhamento":"CENTER",
    "cor":-16777216,
    "habilitar":false,
    "posicaoEixoX":10.0,
    "posicaoEixoY":20.0,
    "tamanhoFonte":15.0,
    "texto":"Linha"
  },
  "eixoX":{  
    "corGrade":-16777216,
    "espessuraGrade":"FINO",
    "exibirGrade":false,
    "exibirLabel":false,
    "formatacao":"",
    "habilitado":false,
    "label":{  
      "cor":-16777216,
      "habilitar":false,
      "posicaoEixoX":0.0,
      "posicaoEixoY":0.0,
      "tamanhoFonte":14.0,
      "texto":"Eixo X"
    },
    "linhaLimite":{  
      "corLinha":-65536,
      "descricao":{  
        "alinhamento":"CENTER",
        "cor":-16777216,
        "habilitar":true,
        "posicaoEixoX":0.0,
        "posicaoEixoY":0.0,
        "tamanhoFonte":15.0,
        "texto":"Limite"
      },
      "espessuraLinha":"FINO",
      "habilitado":true,
      "tipoPontilhado":"LONGO",
      "tipoPosicaoDescricao":"RIGHT_TOP",
      "valorLimite":10.0
    },
    "tipoEixo":"EIXO_X",
    "tipoFormatacao":"MONETARIO",
    "valorMaximo":12.0,
    "valorMinimo":0.0
  },
  "eixoY":{  
    "corGrade":-16777216,
    "espessuraGrade":"FINO",
    "exibirGrade":false,
    "exibirLabel":true,
    "formatacao":"",
    "habilitado":false,
    "label":{  
      "cor":-16777216,
      "habilitar":false,
      "posicaoEixoX":0.0,
      "posicaoEixoY":0.0,
      "tamanhoFonte":14.0,
      "texto":"EIXO_Y_ESQUERDA"
    },
    "linhaLimite":{  
      "corLinha":-65536,
      "descricao":{  
        "alinhamento":"CENTER",
        "cor":-16777216,
        "habilitar":true,
        "posicaoEixoX":0.0,
        "posicaoEixoY":0.0,
        "tamanhoFonte":15.0,
        "texto":"Limite"
      },
      "espessuraLinha":"FINO",
      "habilitado":false,
      "tipoPontilhado":"LONGO",
      "tipoPosicaoDescricao":"RIGHT_TOP",
      "valorLimite":1500.0
    },
    "tipoEixo":"EIXO_Y_ESQUERDA",
    "tipoFormatacao":"MONETARIO",
    "valorMaximo":767.4,
    "valorMinimo":1.0
  },
  "estilo":{  
    "corDaBorda":-16777216,
    "corDeFundo":0,
    "corDeFundoGrade":0,
    "corLegendas":-16777216,
    "espessuraBorda":"FINO",
    "exibirBordas":false,
    "exibirGradeDeFundo":false,
    "habilitarLegendas":true,
    "tamanhoTextoLegendas":"NORMAL"
  },
  "habilitarArrastar":false,
  "habilitarBuracoCentroPizza":false,
  "habilitarDestaqueAoToquePizza":true,
  "habilitarGirarAoToque":false,
  "habilitarToque":false,
  "habilitarValoresPorPorcentagemPizza":false,
  "habilitarZoom":false,
  "incluirDescricaoDentroDoGrafico":false,
  "larguraBarra":0.8,
  "porcentagemRaioCentroPizza":50.0,
  "porcentagemTransparenciaCentroPizza":55.0,
  "tamanhoDestaquePorcaoSelecionadaPizza":18.0,
  "tipo":"LINHA",
  "tipoAnimacao":"NORMAL"
}};
var dadosGraficoPizza = function(){
    return {  
  "conjutoDados":[  
    {  
      "descricaoConjunto":"",
      "exibirValores":true,
      "listaValores":[  
        {  
          "corItem":-13710223,
          "corTexto":-16711936,
          "descricaoValor":"item-0",
          "hashConjuntoDado":-348958934,
          "valorX":10.0,
          "valorY":0.0
        },
        {  
          "corItem":-932849,
          "corTexto":-16711936,
          "descricaoValor":"item-1",
          "hashConjuntoDado":-348958934,
          "valorX":10.0,
          "valorY":0.0
        },
        {  
          "corItem":-1618884,
          "corTexto":-16711936,
          "descricaoValor":"item-2",
          "hashConjuntoDado":-348958934,
          "valorX":10.0,
          "valorY":0.0
        },
        {  
          "corItem":-13330213,
          "corTexto":-16711936,
          "descricaoValor":"item-3",
          "hashConjuntoDado":-348958934,
          "valorX":10.0,
          "valorY":0.0
        },
        {  
          "corItem":-12560000,
          "corTexto":-16711936,
          "descricaoValor":"item-4",
          "hashConjuntoDado":-348958934,
          "valorX":10.0,
          "valorY":0.0
        },
        {  
          "corItem":-6969988,
          "corTexto":-16711936,
          "descricaoValor":"item-5",
          "hashConjuntoDado":-348958934,
          "valorX":10.0,
          "valorY":0.0
        },
        {  
          "corItem":-2508638,
          "corTexto":-16711936,
          "descricaoValor":"item-6",
          "hashConjuntoDado":-348958934,
          "valorX":10.0,
          "valorY":0.0
        },
        {  
          "corItem":-4225402,
          "corTexto":-16711936,
          "descricaoValor":"item-7",
          "hashConjuntoDado":-348958934,
          "valorX":10.0,
          "valorY":0.0
        },
        {  
          "corItem":-5033904,
          "corTexto":-16711936,
          "descricaoValor":"item-8",
          "hashConjuntoDado":-348958934,
          "valorX":10.0,
          "valorY":0.0
        },
        {  
          "corItem":-2535286,
          "corTexto":-16711936,
          "descricaoValor":"item-9",
          "hashConjuntoDado":-348958934,
          "valorX":10.0,
          "valorY":0.0
        }
      ],
      "tamanhoTextoItens":15.0,
      "tipoFormatacao":"SEM_FORMATACAO"
    }
  ],
  "corCentroPizza":-65536,
  "descricaoGrafico":{  
    "alinhamento":"CENTER",
    "cor":-16777216,
    "habilitar":false,
    "posicaoEixoX":10.0,
    "posicaoEixoY":20.0,
    "tamanhoFonte":15.0,
    "texto":"DESC PIZZA"
  },
  "estilo":{  
    "corDaBorda":-16777216,
    "corDeFundo":-16776961,
    "corDeFundoGrade":0,
    "corLegendas":-16777216,
    "espessuraBorda":"FINO",
    "exibirBordas":false,
    "exibirGradeDeFundo":false,
    "habilitarLegendas":true,
    "tamanhoTextoLegendas":"NORMAL"
  },
  "habilitarArrastar":false,
  "habilitarBuracoCentroPizza":true,
  "habilitarDestaqueAoToquePizza":true,
  "habilitarGirarAoToque":false,
  "habilitarToque":false,
  "habilitarValoresPorPorcentagemPizza":true,
  "habilitarZoom":false,
  "incluirDescricaoDentroDoGrafico":false,
  "larguraBarra":0.0,
  "porcentagemRaioCentroPizza":50.0,
  "porcentagemTransparenciaCentroPizza":0.0,
  "tamanhoDestaquePorcaoSelecionadaPizza":18.0,
  "textoCentroPizza":{  
    "alinhamento":"CENTER",
    "cor":-16777216,
    "habilitar":false,
    "posicaoEixoX":10.0,
    "posicaoEixoY":20.0,
    "tamanhoFonte":15.0,
    "texto":"DESC PIZZA"
  },
  "tipo":"PIZZA",
  "tipoAnimacao":"NORMAL"
}};

var dadosGraficoBarraVertical = function(){
    return {  
    'conjutoDados':[  
        {  
        'descricaoConjunto':'Descricao 1a',
        'exibirValores':true,
        'listaValores':[  
            {  
            'corItem':-65536,
            'corTexto':-16777216,
            'hashConjuntoDado':715913675,
            'valorX':0.0,
            'valorY':0.0
            },
            {  
            'corItem':-65536,
            'corTexto':-16777216,
            'hashConjuntoDado':715913675,
            'valorX':0.0,
            'valorY':1200.0
            }
        ],
        'tamanhoTextoItens':14.0,
        'tipoFormatacao':'MONETARIO'
        },
        {  
        'descricaoConjunto':'Descricao 2a',
        'exibirValores':true,
        'listaValores':[  
            {  
            'corItem':-16776961,
            'corTexto':-16777216,
            'hashConjuntoDado':715914636,
            'valorX':1.0,
            'valorY':0.0
            },
            {  
            'corItem':-16776961,
            'corTexto':-16777216,
            'hashConjuntoDado':715914636,
            'valorX':1.0,
            'valorY':1400.0
            }
        ],
        'tamanhoTextoItens':14.0,
        'tipoFormatacao':'MONETARIO'
        }
    ],
    'corCentroPizza':0,
    'descricaoGrafico':{  
        'alinhamento':'CENTER',
        'cor':-16777216,
        'habilitar':false,
        'posicaoEixoX':10.0,
        'posicaoEixoY':20.0,
        'tamanhoFonte':15.0,
        'texto':'Vertical'
    },
    'eixoX':{  
        'corGrade':-16777216,
        'espessuraGrade':'FINO',
        'exibirGrade':false,
        'exibirLabel':false,
        'formatacao':'',
        'habilitado':false,
        'label':{  
        'cor':-16777216,
        'habilitar':false,
        'posicaoEixoX':0.0,
        'posicaoEixoY':0.0,
        'tamanhoFonte':14.0,
        'texto':'Eixo X'
        },
        'tipoEixo':'EIXO_X',
        'tipoFormatacao':'MONETARIO',
        'valorMaximo':3.0,
        'valorMinimo':0.0
    },
    'eixoY':{  
        'corGrade':-16777216,
        'espessuraGrade':'FINO',
        'exibirGrade':false,
        'exibirLabel':false,
        'formatacao':'',
        'habilitado':false,
        'label':{  
        'cor':-16777216,
        'habilitar':false,
        'posicaoEixoX':0.0,
        'posicaoEixoY':0.0,
        'tamanhoFonte':14.0,
        'texto':'EIXO_Y_ESQUERDA'
        },
        'tipoEixo':'EIXO_Y_ESQUERDA',
        'tipoFormatacao':'MONETARIO',
        'valorMaximo':1680.0,
        'valorMinimo':0.0
    },
    'estilo':{  
        'corDaBorda':-16777216,
        'corDeFundo':0,
        'corDeFundoGrade':0,
        'corLegendas':-16777216,
        'espessuraBorda':'FINO',
        'exibirBordas':false,
        'exibirGradeDeFundo':false,
        'habilitarLegendas':true,
        'tamanhoTextoLegendas':'NORMAL'
    },
    'habilitarArrastar':false,
    'habilitarBuracoCentroPizza':false,
    'habilitarDestaqueAoToquePizza':true,
    'habilitarGirarAoToque':false,
    'habilitarToque':false,
    'habilitarValoresPorPorcentagemPizza':false,
    'habilitarZoom':false,
    'incluirDescricaoDentroDoGrafico':false,
    'larguraBarra':0.8,
    'porcentagemRaioCentroPizza':50.0,
    'porcentagemTransparenciaCentroPizza':55.0,
    'tamanhoDestaquePorcaoSelecionadaPizza':18.0,
    'tipo':'BARRA_VERTICAL',
    'tipoAnimacao':'NORMAL'
    };
}

exports.barraVertical = function(callback){
    callback(dadosGraficoBarraVertical());
};

exports.barraHorizontal = function(callback){
    callback(dadosGraficoBarraHorizontal());
};

exports.linha = function(callback){
    callback(dadosGraficoLinha());
};

exports.pizza = function(callback){
    callback(dadosGraficoPizza());
};